### PR TITLE
Adding support for detection of binary files

### PR DESCRIPTION
**Pull request by mariosotil**
I added the `is_test` function, to detect if the data is binary or text. This is useful to post binary files to endpoints from resources like API Gateway.

I use `awscurl` with this alias in .bash_profile

    alias awscurl='docker run --rm -it -v "/home/$USER/.aws:/root/.aws" -v "`pwd`:/current" -e PYTHONPATH="/" --workdir "/current" "$USER/awscurl:latest" "$@"'

So, I called it like this:

    $ awscurl --service execute-api --region us-east-1 --header "Content-Type: image/jpeg" -X POST -d @FILE.jpg https://xxxxxxxxxxx.execute-api.us-east-1.amazonaws.com/stage/method

### CODE REVIEW

**Comment by okigan** [comment]
@mariosotil see error message and "Details" links above -- looks like code style checks and unit tests are failing -- please resolve and push updated commit

**Comment by okigan** [comment]
@mariosotil instead of detection (which fails sometimes and would require flag to override), should this  just be a command line flag?

**Comment by mariosotil** [comment]
@okigan a flag sounds better. I will improve it and fix the Python3 problems 👍

**Comment by mariosotil** [comment]
@okigan I named the flag `--binary-payload`. Please, let me know if you agree with that name or there's a better one.

Anyway, I will add tests for this flag until tomorrow.

**Comment by okigan** [comment]
Did some searching, curl already has a flag for this, so seems worthwhile to re-use that: --data-binary

https://unix.stackexchange.com/questions/77588/passing-binary-data-to-curl-without-using-a-file

**Comment by mariosotil** [comment]
I'm on it.

**Comment by mariosotil** [comment]
@okigan I did it. Also, I wrote the tests and fixed some bugs about the binary data. Let me know if there is something else to fix.

**Comment by okigan** [comment]
looks good to me -- I'll merge on Monday unless something else comes to mind

**Comment by okigan** [comment]
@mariosotil thanks for PR and updates

**Comment by mariosotil** [comment]
@okigan Happy to help :-)

**Pull request merged**
