### PR TITLE
Don't log unless verbose arg is passed in

### PR DESCRIPTION
**Pull request by ajmath**
Changes log method to only output when verbose is set.  This enables redirection into other scripts, files, etc.

### CODE REVIEW

**Comment by okigan** [comment]
also please resolve conflict

**Comment by ajmath** [comment]
Any chance of getting this merged in?

**Comment by okigan** [comment]
hmm, not too happy with the global... but I'll proceed (begrudgingly :))

**Comment by ajmath** [comment]
Thanks!

**Comment by ajmath** [comment]
I didn't like the global either but not doing so would have been a huge refactor.

**Comment by okigan** [comment]
published: https://pypi.python.org/pypi/awscurl/0.11

**Pull request merged**
