### PR TITLE
fix: exit code not passed to sys.exit

### PR DESCRIPTION
**Pull request by jackie-linz**
fixes: #208 

tested locally

```shell
$ python3 -m awscurl --service lambda https://<my-function-url>.lambda-url.ap-southeast-2.on.aws/
{"data":"Hello from Lambda!"}
$ echo $?
1
```

### CODE REVIEW

**Comment by okigan** [comment]
hmm, maybe that should follow curl's logic: 

https://curl.se/docs/manpage.html#-f

key part:  `By default, curl does not consider HTTP response codes to indicate failure.`

**Comment by jackie-linz** [comment]
That's fair, should I add `-f`/`--fail` option then?

**Comment by jackie-linz** [comment]
actually, `--fail-with-body` may be closer to what `awscurl` is doing...

**Comment by okigan** [comment]
Sounds good -- please update pr

**Comment by jackie-linz** [comment]
done, tested locally

```shell
$ python3 -m awscurl --service lambda https://<my-function>.lambda-url.ap-southeast-2.on.aws/ 
{"data":"Hello from Lambda!"}
$ echo $?
0

$ python3 -m awscurl --fail-with-body --service lambda https://<my-function>.lambda-url.ap-southeast-2.on.aws/ 
{"data":"Hello from Lambda!"}
$ echo $?
22
```

**Comment by okigan** [comment]
@jackie-linz new release published

**Pull request merged**
