### PR TITLE
Include user-specified signed headers

### PR DESCRIPTION
**Pull request by MegaWattSec**
This allows users to include additional signed headers by specifying them with the "x-amz-" prefix. Such as "x-amz-target". So far as I have seen, no AWS service expects signed headers that do not include that prefix.

Addresses issue #149.

### CODE REVIEW

**Comment by okigan** [comment]
@MegaWattSec thanks, please resolve build/lint issues.

**Comment by okigan** [comment]
@MegaWattSec looks like CI is not happy, please have a look

**Comment by MegaWattSec** [comment]
Pytest is passing a string for the "headers" value when it should be a dictionary. Do I need to make a condition for that edge case when the only way it can happen is via testing? Or should the test be fixed?

**Comment by okigan** [comment]
hmm, interesting - let me re-review the test.

**Comment by okigan** [comment]
@MegaWattSec I think you are right, I've updated the test: https://github.com/okigan/awscurl/pull/202. I think you can rebase atop latest main/master.

**Pull request merged**
